name: test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-16.04, ubuntu-20.04, windows-2019, macos-10.15]
        os: [ubuntu-20.04]
        python-version: [2.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      # TODO: `pip install flake8 pytest`
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install
      run: |
        python setup.py install

    - name: Install utils for testing on Ubuntu or Debian
      # libxml2-utils gets us xmllint
      shell: bash -l {0}
      run: |
        sudo apt-get install -y libxml2-utils

    - name: Install dependencies for testing
      run: |
        pip install matplotlib

    - name: Run test
      run: |
        cd test
        python test1.py
        python test2.py
        python test3.py
        python test4.py
        python test5.py
        python test-issue8.py

    # - name: Test with pytest
    #   run: |
    #     pytest
